name: leancode_cubit_utils
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  cqrs: ^10.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  leancode_hooks: ^0.0.6
  leancode_lint: ^6.0.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter: