name: leancode_cubit_utils
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cqrs: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter: